### ISSUE TITLE
Windows Runtime metadata validation failed

### ISSUE THREAD

**Issue by Tlaster** [ProjectMarduk/Marduk.Controls#10]
> Error Found: The general metadata correctness test detected the following errors:
> Parameter __returnValue of method GetVisableItems of type Marduk.Controls.ILayout in file Marduk.Controls.winmd references the non-Windows Runtime type IntPtr. Windows Runtime types can reference only Windows Runtime types.
> Parameter __returnValue of method get_VisableItems of type Marduk.Controls.__IOrientedVirtualizingPanelProtectedNonVirtuals in file Marduk.Controls.winmd references the non-Windows Runtime type IntPtr. Windows Runtime types can reference only Windows Runtime types.
> Parameter __returnValue of method get_VisableItems of type Marduk.Controls.OrientedVirtualizingPanel in file Marduk.Controls.winmd references the non-Windows Runtime type IntPtr. Windows Runtime types can reference only Windows Runtime types.

**Comment by validvoid** [comment]
@Tlaster Where did you get this error from? WACK?

**Comment by Tlaster** [comment]
@validvoid Actually from Store Application Review Results
